baseURL = 'https://ratul0.github.io/swift-book/'
title = 'Swift & iOS Development'
theme = 'hugo-book'

# Book configuration
disableKinds = ['taxonomy', 'term']
defaultContentLanguage = 'en'
enableGitInfo = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'auto'
  
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true
  
  # (Optional, default false) Enables search function with lunr.js
  BookSearch = true
  
  # (Optional, default false) Enables comments template on pages
  BookComments = false
  
  # (Optional, default docs) Specify root page to render child pages as menu.
  BookSection = 'docs'
  
  # Set source repository location.
  BookRepo = 'https://github.com/YOUR-USERNAME/swift-book'
  
  # Specifies commit portion of the link to the page's last modified commit hash for 'doc' page
  BookCommitPath = 'commit'
  
  # Enable "Edit this page" links for 'doc' page type.
  BookEditPath = 'edit/main'
  
  # (Optional, default January 2, 2006) Configure the date format used on the pages
  BookDateFormat = 'January 2, 2006'
  
  # (Optional, default true) Enables search in book menu.
  BookMenuBundle = '/menu'
  
  # (Optional, default true) Shows a logo in book menu.
  # BookLogo = '/logo.png'
  
  # Configure the book's title, subtitle and description for better SEO
  description = 'A comprehensive guide to Swift programming and iOS development, from fundamentals to production patterns.'
  author = 'Your Name'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[menu]
  [[menu.after]]
    name = 'GitHub'
    url = 'https://github.com/YOUR-USERNAME/swift-book'
    weight = 10
  [[menu.after]]
    name = 'Download PDF'
    url = '#'
    weight = 20